config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/technews', to: 'pages#tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def self.special_blogs
    all
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new

    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Your post is now live." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def toggle_status
     if @blog.draft?
      @blog.published!
     elsif @blog.published?
      @blog.draft!
     end

     redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<article class="blog-post">
  <h2 class="blog-post-title mb-1"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published
    <%= distance_of_time_in_words(blog.created_at, Time.now) %>
    ago</p>
  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog) if logged_in?(:site_admin) %>
      /
      <%= link_to "Edit", edit_blog_path(blog) if logged_in?(:site_admin) %>
      /
      <%= if logged_in?(:site_admin)
        button_to "Delete Post", blog, method: :delete, class: "blog-delete-btn"
      end %>
    </p>
  <% end %>
  <p>
    <%= blog.body %>
  </p>
</article>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, class: "needs-validation", novalidate: true) do |form| %>
  <% if blog.errors.any? %>
     <% blog.errors.full_messages.each do |error|  %>
       <%= js add_gritter(error, :title => "Mohamed Cake Portfolio", sticky: false) %>
     <% end %>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
    <div class="invalid-feedback">
      Please provide a title.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :topic_id, class: "form-label" %>
    <%= form.collection_select(
      :topic_id,
      Topic.all,
      :id,
      :title,
      { include_blank: true },
      { class: "form-select"}
    ) %>
    <div class="invalid-feedback">
      Please select a topic.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control", rows: 15%>
    <div class="invalid-feedback">
      Please provide a body.
    </div>
  </div>

  <div class="mb-3">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %>
  |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<%= paginate @blogs %>

<%= render @blogs %>

<%= paginate @blogs %>

app/views/blogs/new.html.erb
<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<h2><%= @blog.title %></h2>

<%= link_to "Edit", edit_blog_path(@blog) if logged_in?(:site_admin) %>

<p>
  <%= @blog.body %>
</p>

<%= render 'comments/comment_form' %>

<div id="comments" data-blog-id="<%= @blog.id %>">
  <%= render @blog.comments %>
</div>