config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/technews', to: 'pages#tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies,
                                 allow_destroy: true,
                                 reject_if: lambda { |attrs| attrs['name'].blank?}

  has_one_attached :main_image
  has_one_attached :thumb_image

  include Placeholder
  validates :title, presence: true
  validates :body, presence: true
  validates :main_image, presence: true
  validates :thumb_image, presence: true

  def self.anguler
    where(subtitle: 'Anguler')
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on rails')}

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[edit update show destroy]
  skip_before_action :verify_authenticity_token
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render json: { status: "updated" }
  end

  def new
   @portfolio_items = Portfolio.new
  end

  def edit
  end

  def update
    @portfolio_items = set_portfolio_item
    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "The record successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: 'Your post is now live.'}
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @portfolio_item = set_portfolio_item
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Record was removed '}
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: %i[id name _destroy]
                                    )
  end

  def set_portfolio_item
    @portfolio_items = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(portfolio_items) do |form| %>
  <% if portfolio_items.errors.any? %>
     <% portfolio_items.errors.full_messages.each do |error|  %>
       <%= js add_gritter(error, :title => "Mohamed Cake Portfolio", sticky: false) %>
     <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :title, style: "display: block", class: "form-label" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :subtitle, style: "display: block", class: "form-label" %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :main_image, class: "form-label" %>
        <%= form.file_field :main_image, class: "form-control", id: "formFile" %>
      </div>

      <div class="mb-3">
        <%= form.label :thumb_image, class: "form-label" %>
        <%= form.file_field :thumb_image, class: "form-control", id: "formFile" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="mb-3">
        <%= form.label :body, style: "display: block", class: "form-label" %>
        <%= form.text_area :body, class: "form-control", rows: 10 %>
      </div>
    </div>
    <hr>
    <div class="col-md-12">
      <h2>Technologies Used:</h2>
      <div class="mb-3" id="technologies">
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>
        <div>
          <%= link_to_add_association 'Add Technology', form, :technologies %>
          <%#= debugger %>
        </div>
      </>

      <div class="mb-3">
        <%= form.submit 'Save Portfolio Item', class: "btn btn-primary w-100" %>
      </div>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col" data-id="<%= portfolio_item.id %>" >
    <div class="card shadow-sm">
        <%# binding.pry %>
        <%= image_tag url_for(portfolio_item.thumb_image.variant(resize_to_fill: [350, 200])), class: "bd-placeholder-img card-img-top" %>

        <%= if logged_in?(:site_admin)
        button_to "Delete Portfolio", portfolio_item, method: :delete, class: "blog-delete-btn"
      end %>
        <div class="card-body">
            <p class="card-text">
                <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span> <%= portfolio_item.subtitle %>
            </p>
            <p class="card-body">
            <%= portfolio_item.body %>
            </p>
            <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">Source</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Live</button>
            </div>
            <small class="text-body-secondary">9 mins</small>
            </div>
        </div>
    </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="mb-3 nested-fields">
  <%= f.label :name, class: 'form-label'%>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association "Remove Technology", f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
    <h1>Edit this Portfolio Item</h1>

    <%= render 'form', portfolio_items: @portfolio_items %>
</div>

app/views/portfolios/index.html.erb
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 <%= "sortable" if logged_in?(:site_admin) %>">
    <%= render partial: 'portfolio_item', collection: @portfolio_items %>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
    <h1>Create a new Portfolio Item</h1>

    <%= render 'form', portfolio_items: @portfolio_items %>
</div>

app/views/portfolios/show.html.erb
<div class="row">
  <div class="col-md-7">
    <%= image_tag url_for(@portfolio_items.thumb_image.variant(resize_to_fill: [350, 200])), class: "bd-placeholder-img card-img-top" %>

  </div>
  <div class="col-md-5">
    <h1><%= @portfolio_items.title %></h1>

    <hr>

    <em><%= @portfolio_items.subtitle %></em>

    <p><%= @portfolio_items.body %></p>

    <hr>

    <h3>Technologies</h3>

    <% @portfolio_items.technologies.each do |t| %>
    <p><%= t.name %></p>
    <% end %>
    <% if logged_in?(:site_admin) %>
      <div class"col-md-12">
        <%= link_to "Edit Item", edit_portfolio_path(@portfolio_items), class: 'btn btn-warning' %>
      </div>

      <% end %>

</div>