config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get '/technews', to: 'pages#tech_news'
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  root to: 'pages#home'
end

app/views/partials/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], :title => "Mohamed Cake Portfolio", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], :title => "Mohamed Cake Portfolio", sticky: false) %>
<% else %>
  <%= js add_gritter(flash[:notice], :title => "Mohamed Cake Portfolio", sticky: false) %>
<% end %>

app/views/partials/_application_nav.html.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0"><%= link_to "CAKE.", root_path, class: "text-decoration-none text-white" %></h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <%= nav_generator 'nav-link fw-bold py-1 px-0  app-nav', 'span' %>
      <%= login_helper "nav-link fw-bold py-1 px-0 navb-button"%>
    </nav>
  </div>
</header>

app/views/partials/_blog_footer.html.erb
<footer class="blog-footer">
    <%= copyright_generator %>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/partials/_blog_masthead.html.erb
<div class="blog-header">
    <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <%= link_to "Write a New Blog", new_blog_path if logged_in?(:site_admin) %>
    </div>
</div>

app/views/partials/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "CAKE.", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <%= nav_generator 'nav-link', 'li' %>
        <li class="nav-item helper-buttons">
          <%= login_helper 'nav-link navb-button' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_blog_sidebar.html.erb
<div class="col-md-4">
    <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-body-tertiary rounded">
            <h4 class="fst-italic">About</h4>
            <p class="mb-0">Welcome to my web development blog! As the sole creator and writer of this blog, I'm excited to share my passion for web development with you. This blog is dedicated to exploring various aspects of web development, including front-end and back-end technologies, web design, user experience, and more.</p>
        </div>


        <div class="p-4">
            <h4 class="fst-italic">Elsewhere</h4>
            <ol class="list-unstyled">
            <li><a href="#"><i class="bi bi-github sidebar-icons"></i></a></li>
            <li><a href="#"><i class="bi bi-linkedin sidebar-icons"></i></a></li>
            <li><a href="#"><i class="bi bi-envelope-at-fill sidebar-icons"></i></a></li>
            </ol>
        </div>
        </div>
    </div>
</div>

app/views/partials/_footer.html.erb
  <footer class="mt-auto text-white-50">
    <p class="app-footer"><%= copyright_generator  %></p>
  </footer>

app/views/partials/_navbar.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/partials/_portfolio_footer.html.erb
<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <%= link_to "View All Portfolio Items", portfolios_path %>/
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1"><%= copyright_generator %></p>
    </div>
</footer>

app/views/partials/_portfolio_masthead.html.erb
<section class="py-5 text-center container">
    <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
            <h1 class="fw-light">My Portfolio</h1>
            <p class="lead text-body-secondary">"The future belongs to those who believe in the beauty of their dreams." - Eleanor Roosevelt</p>
                <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
                <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
            </p>
        </div>
    </div>
</section>

app/views/partials/_portfolio_nav.html.erb
<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container-nav">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                <h4>About</h4>
                <p class="text-body-secondary">Hello and welcome to my web development portfolio! As a web developer, I'm passionate about creating stunning, user-friendly websites and applications that solve real-world problems. On this page, you'll find a showcase of my web development projects, including responsive designs, dynamic interfaces, and robust backend functionality. </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                <h4>Pages</h4>
                <ul class="list-unstyled">
                    <%= nav_generator 'text-white text-decoration-none', 'li' %>
                    <li class="helper-buttons"><%= login_helper "text-white text-decoration-none navb-button"%></li>
                </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container-nav">
            <strong><%= link_to "CAKE.", root_path, class: "navbar-brand d-flex align-items-center" %></strong>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        </div>
    </div>
</header>